swagger: '2.0'
info:
  version: '0.42'
  title: Dummy example
schemes: [ http ]
basePath: "/api"
paths:
  /echo:
    post:
      x-mojo-to: "echo#index"
      operationId: echo
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Echo response
          schema:
            type: object
    get:
      x-mojo-to: "echo#index"
      operationId: echoGet
      parameters:
      - in: query
        name: q
        type: string
      responses:
        200:
          description: Echo response
          schema:
            type: string
  /user:
    post:
      x-mojo-to: "echo#index"
      operationId: createUser
      parameters:
      - in: body
        name: user
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: Created User
          schema:
            $ref: "#/definitions/User"
definitions:
  User:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
